helmDefaults:
  wait: true
  createNamespace: true

repositories:
  - name: cloudflare
    url: https://cloudflare.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: cloudflared
    namespace: cloudflared
    chart: cloudflare/cloudflare-tunnel
    values:
      - ./values/cloudflared.yml

  - name: kube-prometheus-stack
    namespace: "monitoring"
    chart: prometheus-community/kube-prometheus-stack

  - name: argocd
    chart: argo/argo-cd
    namespace: argocd