replicaCount: 1

image:
  repository: yslanramos/mirim-bot
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "main"

fullnameOverride: "mirim-invertido-bot"

service:
  enabled: false

ingress:
  enabled: false

envFrom:
  - secretRef:
      name: mirim-invertido-env

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe: {}
readinessProbe: {}
autoscaling:
  enabled: false