apiVersion: v1
kind: Service
metadata:
  name: {{ include "wireguard.fullname" . }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: wg-udp
      port: 51820
      protocol: UDP
      targetPort: 51820
    - name: wg-ui
      port: 51821
      protocol: TCP
      targetPort: 51821
  selector:
    {{- include "wireguard.selectorLabels" . | nindent 4 }}
