apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namespace.name }}-namespace
  namespace: "argocd"
  annotations:
    argocd.argoproj.io/sync-wave: 300
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: {{ .Values.namespace.name }}-namespace
      {{- with .Values.namespace }}
      values: | 
        {{- toYaml . | nindent 8 }}
      {{- end }}
    repoURL: git@github.com:Tsugami/homelab.git
    targetRevision: main
    path: ./apps/namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
      backoff:
        duration: 15s
        factor: 1